spring:
  application:
    name: SportShop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: 123123
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 867628799689-oautu3cfi7111jdbj163aoeksd8u9utp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          github:
            client-id: Ov23liN2dset7YaLyoaU
            client-secret: 7a8872adcdf200fc92ea7bc709e342d65b89b213
            scope:
              - user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
server:
  port: 8989
debug: true